apisix:
  node_listen: 9080
  enable_ipv6: false

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
    
wasm:
  plugins:
  - name: my-first-plugin
    priority: 99
    file: /wasm/my_first_plugin.wasm
#END
